---
title: "data_wrangling_ii"
output: html_document
date: "2023-01-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rvest)
library(httr)
```


If the website have tables

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)


table = 
  drug_use_html %>%
  html_table() %>%
  first() %>%
slice(-1)
```




```{r}
url = "https://www.bestplaces.net/cost_of_living/city/new_york/new_york"
cost_of_living_html = read_html(url) %>%
  html_table(header = TRUE) %>%
  first() 
  


```




using select gadget to import data



```{r}
swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/") 




```


```{r}
title = 
  swm_html %>%
  html_elements(".lister-item-header a") %>%
  html_text


gross_revenue = 
  swm_html %>%
  html_elements(".text-small:nth-child(7) span:nth-child(5)") %>%
  html_text()

runtime = 
  swm_html %>%
  html_elements(".runtime") %>%
  html_text



swm_df =
  tibble(
    title = title,
    revenue = gross_revenue,
    runtime = runtime,
  )


```




```{r}

url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

Napoleon_html = read_html(url)

Nap_titles =
 Napoleon_html %>%
  html_elements(".a-text-bold span") %>%
  html_text

Nap_reviews =
 Napoleon_html %>%
  html_elements(".review-text-content span") %>%
  html_text

Nap_stars = 
  Napoleon_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text

Nap_df = 
  tibble(
   titles = Nap_titles,
   reviews = Nap_reviews,
   stars = Nap_stars
  )

```





```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_elements(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_elements("#cm_cr-review_list .review-rating") %>%
  html_text()

review_text = 
  dynamite_html %>%
  html_elements(".review-text-content span") %>%
  html_text()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```




Using API to import data


```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>%
  content("parsed")

nyc_water =
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>%
  content("text") %>%
  jsonlite::fromJSON() %>%
  as_tibble()

```




```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>%
  content("parsed")



```



```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name

poke[["abilities"]]

 
```




































